### ISSUE TITLE
IDE is stuck.

### ISSUE THREAD

**Issue by chenkamin** [oxygenhq/oxygen-ide#169]
Hey, 
Start working with the IDE today.
Every time the test fails the IDE get stuck.
It is a common bug? any ideas? 
More info,
i run it on ubuntu, on chrome.
Would like to help to fix it. 
:) 
Chen

**Comment by ndimer** [comment]
Hi Chen,

Could you please include the following information:

- Oxygen IDE version
- Screenshot when IDE gets stuck
- Log file (Help -> View Log)

**Comment by chenkamin** [comment]
1.
Oxygen IDE 1.14.0
Oxygen: 1.0.1
Electron: 3.1.13
Node: 10.2.0
Arch: X64

2.
![Screenshot from 2020-02-10 09-15-03](https://user-images.githubusercontent.com/40539832/74128486-f9471280-4be5-11ea-8fca-2d18c7e628d8.png)

logs

INFO: 2020-02-10 09:13:09 Service call: FileService.getFileInfo [ '/home/chenkamin/.config/Oxygen IDE/logs/oxygenide-2020-02-10.log' ]
INFO: 2020-02-10 09:13:09 Service call: FileService.getFileContent [ '/home/chenkamin/.config/Oxygen IDE/logs/oxygenide-2020-02-10.log' ]
INFO: 2020-02-10 09:13:34 Service call: DeviceDiscoveryService.stop []
INFO: 2020-02-10 09:13:34 Service call: TestRunnerService.start [ 'tests/oxyganTest2.js',
  {},
  { iterations: 1,
    paramFilePath: null,
    paramMode: 'sequential',
    reopenSession: false,
    rootPath: '/home/chenkamin/Documents/projects/cisoteria-web/testing',
    seleniumPort: 37115,
    stepDelay: 0,
    testMode: 'web',
    testProvider: null,
    testTarget: 'chrome' } ]
INFO: 2020-02-10 09:13:34 Service call: AnalyticsService.playStart [ { browserName: 'chrome', provider: 'Local' } ]
INFO: 2020-02-10 09:13:37 Oxygen Worker initialized in 2110 ms
INFO: 2020-02-10 09:13:37 Test 4792aeb5 has started...
INFO: 2020-02-10 09:13:37 Suite "oxyganTest2" has started...
INFO: 2020-02-10 09:13:37 - Case "oxyganTest2" has started...
INFO: 2020-02-10 09:13:38   - Step "init" has started...
INFO: 2020-02-10 09:13:40   - Step "web.init()" has ended in 2.12s with status: PASSED.
INFO: 2020-02-10 09:13:40   - Step "open" has started...
INFO: 2020-02-10 09:13:53   - Step "web.open("http://c28.cisoteria.com/login")" has ended in 12.97s with status: PASSED.
INFO: 2020-02-10 09:13:53   - Step "open" has started...
INFO: 2020-02-10 09:13:54   - Step "web.open("http://c28.cisoteria.com/login")" has ended in 0.82s with status: PASSED.
INFO: 2020-02-10 09:13:54   - Step "selectWindow" has started...
INFO: 2020-02-10 09:13:54   - Step "web.selectWindow("title=Cisoteria")" has ended in 0.03s with status: PASSED.
INFO: 2020-02-10 09:13:54   - Step "click" has started...
INFO: 2020-02-10 09:13:54   - Step "web.click("id=mat-input-0")" has ended in 0.20s with status: PASSED.
INFO: 2020-02-10 09:13:54   - Step "type" has started...
INFO: 2020-02-10 09:13:54   - Step "web.type("id=mat-input-0","Mail")" has ended in 0.27s with status: PASSED.
INFO: 2020-02-10 09:13:54   - Step "type" has started...
INFO: 2020-02-10 09:13:54   - Step "web.type("id=mat-input-1","Pass1")" has ended in 0.21s with status: PASSED.
INFO: 2020-02-10 09:13:54   - Step "click" has started...
INFO: 2020-02-10 09:13:54   - Step "web.click("name=submit")" has ended in 0.18s with status: PASSED.
INFO: 2020-02-10 09:13:54   - Step "click" has started...
INFO: 2020-02-10 09:13:55   - Step "web.click("id=mat-input-2")" has ended in 0.39s with status: PASSED.
INFO: 2020-02-10 09:13:55   - Step "type" has started...
INFO: 2020-02-10 09:13:55   - Step "web.type("id=mat-input-2","PASS")" has ended in 0.13s with status: PASSED.
INFO: 2020-02-10 09:13:55   - Step "click" has started...
INFO: 2020-02-10 09:13:55   - Step "web.click("name=submit")" has ended in 0.12s with status: PASSED.
INFO: 2020-02-10 09:13:55   - Step "click" has started...
INFO: 2020-02-10 09:13:57   - Step "web.click("//div[@id='buildingBlocksMenu']")" has ended in 1.78s with status: PASSED.
INFO: 2020-02-10 09:13:57   - Step "click" has started...
INFO: 2020-02-10 09:13:57   - Step "web.click("//div[@id='usersMenu']")" has ended in 0.48s with status: PASSED.
INFO: 2020-02-10 09:13:57   - Step "click" has started...
INFO: 2020-02-10 09:13:59   - Step "web.click("//a/span/img")" has ended in 1.89s with status: PASSED.
INFO: 2020-02-10 09:13:59   - Step "click" has started...
INFO: 2020-02-10 09:14:00   - Step "web.click("name=fname")" has ended in 0.37s with status: PASSED.
INFO: 2020-02-10 09:14:00   - Step "type" has started...
INFO: 2020-02-10 09:14:00   - Step "web.type("name=fname","JJ")" has ended in 0.48s with status: PASSED.
INFO: 2020-02-10 09:14:00   - Step "type" has started...
INFO: 2020-02-10 09:14:00   - Step "web.type("name=lname","KOKL")" has ended in 0.28s with status: PASSED.
INFO: 2020-02-10 09:14:00   - Step "click" has started...
INFO: 2020-02-10 09:14:01   - Step "web.click("mat-select[name=jobTitle]")" has ended in 0.39s with status: PASSED.
INFO: 2020-02-10 09:14:01   - Step "click" has started...
INFO: 2020-02-10 09:14:01   - Step "web.click("//mat-option[2]/span/span")" has ended in 0.50s with status: PASSED.
INFO: 2020-02-10 09:14:01   - Step "click" has started...
INFO: 2020-02-10 09:14:53 Service call: TestRunnerService.stop []
INFO: 2020-02-10 09:15:50 Logs file location : /home/chenkamin/.config/Oxygen IDE/logs/oxygenide-2020-02-10.log
ERROR: 2020-02-10 09:15:50 (node:32259) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
INFO: 2020-02-10 09:15:51 Main process has started
INFO: 2020-02-10 09:15:52 Service call: UpdateService.start [ false ]
INFO: 2020-02-10 09:15:52 UpdateService start false
INFO: 2020-02-10 09:15:52 Service call: SeleniumService.start []
INFO: 2020-02-10 09:15:52 Service call: DeviceDiscoveryService.start []
INFO: 2020-02-10 09:15:52 Service call: RecorderService.watch []
INFO: 2020-02-10 09:15:52 Service call: FileService.createWatchOnFilesChannel [ 'testing' ]
WARN: 2020-02-10 09:15:55 Unable to retrieve Android device list. Error: Could not find 'adb' in PATH. Please set the ANDROID_HOME or ANDROID_SDK_ROOT environment variables to the corect Android SDK root directory path.
    at d.m.getBinaryFromPath (/home/chenkamin/Downloads/oxygen-1.14.0-linux-x64/resources/app/main/webpack:/app/main/main.prod.js:24:305650)
INFO: 2020-02-10 09:15:55 Service call: AnalyticsService.setUser [ 'b74b1936-0c22-4988-8a7a-8baa3c7d1135' ]
INFO: 2020-02-10 09:15:55 Service call: CloudProvidersService.start []
INFO: 2020-02-10 09:15:55 Service call: VisualTestingProvidersService.start []
INFO: 2020-02-10 09:15:55 Service call: VisualTestingProvidersService.updateProviderSettings [ 'applitools',
  { accessKey: null,
    checkOnEveryAction: false,
    inUse: false,
    title: 'Applitools' } ]
INFO: 2020-02-10 09:15:55 Found Chrome at:  [ '/usr/bin/google-chrome-stable', '/usr/bin/google-chrome' ]
INFO: 2020-02-10 09:15:55 Found Chrome version: 77
INFO: 2020-02-10 09:15:55 Required ChromeDriver version: 77.0.3865.40
INFO: 2020-02-10 09:15:55 Found matching ChromeDriver at /home/chenkamin/.config/Oxygen IDE/drivers/chromedriver-77.0.3865.40/chromedriver
INFO: 2020-02-10 09:15:55 Attempting to start Selenium process with the following args: [ '-jar',
  '-Dwebdriver.gecko.driver="linux/geckodriver"',
  '-Dwebdriver.chrome.driver="/home/chenkamin/.config/Oxygen IDE/drivers/chromedriver-77.0.3865.40/chromedriver"',
  'selenium-server-standalone-3.141.59.jar',
  '-port',
  '39751' ]
INFO: 2020-02-10 09:15:56 _emitStartedEvent 39751
INFO: 2020-02-10 09:15:56 Service call: FileService.getFolderContent [ 'testing' ]
INFO: 2020-02-10 09:15:56 203
INFO: 2020-02-10 09:15:56 checkForUpdate 203
INFO: 2020-02-10 09:15:56 Service call: FileService.createWatchOnFilesChannel [ 'testing' ]
INFO: 2020-02-10 09:15:56 Service call: FileService.returnFileContent [ 'config.json' ]
INFO: 2020-02-10 09:15:56 Service call: FileService.returnFileContent [ 'config.json' ]
INFO: 2020-02-10 09:15:56 Service call: FileService.returnFileContent [ 'logIn.test.js' ]
INFO: 2020-02-10 09:15:56 Service call: FileService.returnFileContent [ 'logIn.test.js' ]
INFO: 2020-02-10 09:15:56 Service call: FileService.returnFileContent [ 'login.js' ]
INFO: 2020-02-10 09:15:56 Service call: FileService.returnFileContent [ 'login.js' ]
INFO: 2020-02-10 09:15:56 Service call: FileService.returnFileContent [ 'oxyganTest2.js' ]
INFO: 2020-02-10 09:15:56 Service call: FileService.returnFileContent [ 'oxyganTest2.js' ]
INFO: 2020-02-10 09:15:56 Service call: FileService.returnFileContent [ 'oxygen.js' ]
INFO: 2020-02-10 09:15:56 Service call: FileService.returnFileContent [ 'oxygen.js' ]
INFO: 2020-02-10 09:16:16 Service call: FileService.getFileContent [ '/home/chenkamin/.config/Oxygen IDE/logs/oxygenide-2020-02-10.log' ]

**Comment by romovs** [comment]
@chenkamin Does it get stuck for more than 1 minute? If it's just 1 minute, then it's an expected behaviour. If element couldn't be found, then all commands wait for one minute for element to appear and only then fail.
The wait timeout can be controlled using `web.setTimeout()` command.

**Comment by chenkamin** [comment]
Today im not facing any "stuck" situations.
The test fails and everything is ok.
Will let you know if this issue will come back, and of course i will try the setTimeOut command.

thanks/
