### ISSUE TITLE
Oxygen IDE not installing with OpenJDK

### ISSUE THREAD

**Issue by pjdaye** [oxygenhq/oxygen-ide#190]
Attempting to install Oxygen IDE 1.18.0 on a Windows 10 laptop with OpenJDK 11.0.2 installed fails with the error message:
Java Runtime Environment not installed. Please download and install JRE 8 from: https://www.java.com/en/download.

Corporate rules do not allow use of Oracle's version of Java and there doesn't appear to be an option to install the Oxygen IDE with an open source version.

**Comment by romovs** [comment]
We will release a version with Java 11 support in a few days.

**Comment by romovs** [comment]
Fixed in v1.19.0.
